pipeline

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -15,8 +15,9 @@ jobs:
     runs-on: ubuntu-latest
 
     env:
-      Solution_Name: TCFiapProducerCreateContact/TCFiapProducerCreateContact.sln 
+      Solution_Name: TCFiapProducerCreateContact/TCFiapProducerCreateContact.sln
       IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/tc-fiap-producers-contacts
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -27,6 +28,18 @@ jobs:
         uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 8.0.x
+          
+      - name: Remove existing NuGet source
+        run: dotnet nuget remove source github || echo "Source not found, skipping removal"
+      
+      - name: Configure NuGet credentials
+        run: |
+          dotnet nuget add source "https://nuget.pkg.github.com/caiofabiogomes/index.json" \
+            --name github \
+            --username caiofabiogomes \
+            --password ${{ secrets.SECRET_NUGET_PACKAGES }} \
+            --store-password-in-clear-text
+
 
       - name: Restore and Build
         run: |
@@ -43,7 +56,7 @@ jobs:
       - name: Build and Push Docker Image (Only Release)
         if: matrix.configuration == 'Release'
         run: |
-          docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
+          docker build --build-arg ARG_SECRET_NUGET_PACKAGES=${{ secrets.SECRET_NUGET_PACKAGES }} -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
           docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest
           docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
           docker push ${{ env.IMAGE_NAME }}:latest
